### ISSUE TITLE
Instagram Grabber

### ISSUE THREAD

**Issue by babakmdi** [dotnettools/SharpGrabber#18]
hi sir. how should we use Instagram Grabber ?  i use this code 

  var grabber = MultiGrabber.CreateDefault();
   var result = await grabber.Grab(new Uri("https://www.instagram.com/p/B7JJacRFh37/?igshid=16wmbgm2oa5m9"));
  List <IGrabbed> grabbedResources = result.Resources;

 but i get this error = > 
DotNetTools.SharpGrabber.Exceptions.GrabParseException: 'Failed to obtain metadata from the Instagram page.'

OR

 var grabber = new InstagramGrabber();
 var result = await grabber.Grab(new Uri("https://www.youtube.com/watch?v=b3ChL9mqPkM"));
  IList<IGrabbed> grabbedResources1 = result.Resources;

i get the same error

**Comment by JavidShoaei** [comment]
Hello there

The Instagram grabber doesn't work since Instagram suddenly started to require authentication even for public videos.
I haven't found the time to fix the problem but I think I might be able to do it in a few months.

**Comment by babakmdi** [comment]
do you have any plan for tiktok videos?

**Comment by JavidShoaei** [comment]
It is quite possible. I'll add it to issues.

**Comment by babakmdi** [comment]
thanks JavidShoaei

**Comment by babakmdi** [comment]
Hi Javid, Can We Use Grabber For Twitter?

**Comment by JavidShoaei** [comment]
Hi there. It's not supported yet but it can be easily integrated with the library when implemented.
