### ISSUE TITLE
Add HLS stream decryption support

### ISSUE THREAD

**Issue by JavidShoaei** [dotnettools/SharpGrabber#26]

**Comment by Acromatic** [comment]
Umm why is this empty? Anyway I finally solved the curl 3 malformed error... it has something to do with the (forgive me about to butcher code speak)... it's the coroutine aka task aka it was what I was doing WHILE the grabber was async... it didn't like my parallel task for some reason, which is fine I can rewrite that part, but might be relevant to your work... sorry this is misplaced/offtopic... figured you'd delete this anyway once you saw a blank issue.

**Comment by JavidShoaei** [comment]
@Acromatic  You do know that you could have sent this comment into the issue you opened the other day even though it's closed.
Anyway, honestly I didn't get how you solved the problem; but if you ever found an issue in the library please let me know. :)

**Comment by Acromatic** [comment]
I didn't really, unorthodox autodidact coder over here.. version control is fringe to me, been coding 15 years and I'm playing with youtube and just got on github :/
