### ISSUE TITLE
Curl error 3: <url> malformed

### ISSUE THREAD

**Issue by Acromatic** [dotnettools/SharpGrabber#28]
Curl error 3: <url> malformed

Pretty much says it all, I'm basically using your example and this is a bit of a mystery bug in my project.

```
var grabber = new YouTubeGrabber();
var result = await grabber.GrabAsync(new Uri("<URL of a YouTube video>"));
IList<IGrabbed> grabbedResources = result.Resources;

```
As far as I can tell the fix requires updating curl.
Is this an old example of usage? I noticed the multigrabber doesn't work, am I missing something?

**Comment by Acromatic** [comment]
Attempting to rebuild a current project, I think I updated framework and .net recently I'll see if this fixes it

**Comment by JavidShoaei** [comment]
CURL? Grabbers internally use `HttpClient` from the standard library. I don't understand why a CURL error is being thrown.
I just ran the test `GrabTests.Test_YouTube_Normal` and it passed.
Did you maybe forget to provide an actual YouTube link instead of `"<URL of a YouTube video>"`?

**Comment by Acromatic** [comment]
Several, yeah I read the source and noticed HttpClient, you're right that wouldn't be Curl... must be a script conflict somewhere. My solution was going to be seperate the code but now I'll try wrapping everything in namespace and see what gives.

**Comment by Acromatic** [comment]
I will however explain how I fixed this here though, for future reference. First let me explain the problem, well the answer is in the explanation. So, what I was using Sharp-Grabber (nice name btw) for was to make a youtube player on a render-to-texture asset in unity. So I had thought since CURL was not used in this project but WAS used in unity that it must be the source of the problem. But it wasn't the source of the problem. The problem arose when (because sharp grabber requires an async function) I had two async functions running in parallel, which I've come across examples of, and is fine by itself, however for some reason it was mangling the url or generally bugging things out somehow. It was resulting in an error produced BY sharp grabber.. and I suspect the way sharp grabber is programmed that it's the villain after all. But it's not a major issue since not having multithreaded parallel functions is fairly easy to do, especially when they aren't called by each other... in most cases. However someday someone will read this and realize that it's not sharp grabber reporting back from CURL.. it's CURL sending a message ack that it's connection from you (the user) has been corrupted in such a way that if you wait until morning it will display another message about security and force close that connection, and that is partly what helped me solve it. That and taking the base example and extracting the differences until they ==.

**Comment by JavidShoaei** [comment]
Thanks for the explanation, but after all do you think there's some change that could be made to make SharpGrabber compatible with Unity, if it's not already? I'm saying that because I didn't clearly understand if the problem was something in the code of SharpGrabber that isn't compatible with Unity, or it was a problem with your own code.

**Comment by Acromatic** [comment]
If there is a problem with Sharp Grabber I wouldn't know it, and this is easily worked around so not a big deal. What specifically caused the bug I don't know but it was related to the alignment of my functions. I have since been working without problems.
