### ISSUE TITLE
3 issues

### ISSUE THREAD

**Issue by Acromatic** [dotnettools/SharpGrabber#29]
Actually no I lied, last we spoke you asked me if there were problems with sharp grabber.  And I said no because I couldn't think of it at the time. But there are 3 issues...

1. The multi grabber example is broken
2. The xxx grabbers are obsolete because those sites charge for videos now and locked up shop, of course this was the second or first thing I tried
3. If you're using unity at least, and you compile your own source there are two pesky errors from ffmpeg..
```

NoiseLib::GatherNoiseTypes: Failed to get types from assembly: FFmpeg.AutoGen, Version=4.3.1.0, Culture=neutral, PublicKeyToken=9b7632533a381715 UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes (System.Type[])

NoiseLib::GatherFractalTypes: Failed to get types from assembly: FFmpeg.AutoGen, Version=4.3.1.0, Culture=neutral, PublicKeyToken=9b7632533a381715
UnityEditor.EditorAssemblies:ProcessInitializeOnLoadAttributes (System.Type[])

```

I don't know if you will fix these things, or someone else will, but  do understand I likely need to build in ffmpeg into my project but meh.. needs a lite version without anything but youtube and vimeo and muxed streams only to dump ffmpeg. I hate useless baggage.

**Comment by JavidShoaei** [comment]
I suggest you try the library again. I've released a big update. At least it'll solve the useless baggage issue.
