### ISSUE TITLE
File format issue

### ISSUE THREAD

**Issue by ZuixAlias** [dotnettools/SharpGrabber#32]
For some YouTube videos the grabbed results contain links for more than one .mp4 files with same resolution, which when muxed with the .m4a audio file using MediaMuxer on android, one of them fails. It only happens if files with invalid/unsupported format are passed to the MediaMuxer...tell me if I am missing on knowing something about file formats, else please look into this...

![PossibleIssue](https://user-images.githubusercontent.com/84643454/120766558-f937f800-c537-11eb-9b26-749adbda66d3.jpg)

**Comment by JavidShoaei** [comment]
This is weird. I don't know why YouTube puts these formats alongside.
Please debug and check the resources and compare properties such as iTag etc.
