### ISSUE TITLE
Exception in getting Info form youtube !

### ISSUE THREAD

**Issue by erfankm7** [dotnettools/SharpGrabber#36]
Hi , Javid
First of all thank you for making this lib <3

Second , I have this exception All time ! does YouTube ban IP or something else ?

I try it on my Germany Server but Exception happened again !

`GrabException: Failed to get metadata information from https://youtube.com/get_video_info?video_id=nErrHNfZEAk&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FnErrHNfZEAk&html5=1&c=TVHTML5&cver=6.20180913.`

**Comment by Deep-Winter** [comment]
Same Problem since today with YouTube. Maybe something has changed on YouTube side?

**Comment by babakmdi** [comment]
Same Problem

DotNetTools.SharpGrabber.Exceptions.GrabException: 'Failed to get metadata information from https://youtube.com/get_video_info?video_id=UJ0-i159JrE&eurl=https%3A%2F%2Fyoutube.googleapis.com%2Fv%2FUJ0-i159JrE&html5=1&c=TVHTML5&cver=6.20180913.'

**Comment by JavidShoaei** [comment]
Hello there,
YouTube has applied new limitations as of today. I haven't yet found a solution for this, but I'm on it.

@erfankm7 About the problem of getting this error all the time, YouTube limits the number of videos you can grab for each IP and you can't keep grabbing unless you do some tricks such as constantly changing IP. I don't know much about that.

**Comment by JavidShoaei** [comment]
OK the old way of getting the YouTube video seems not to work anymore. Most other libraries are also broken because of this. However, I'm looking for a new method and I'm close to getting it to work.

**Comment by JavidShoaei** [comment]
The YouTube grabber is now fixed :)

**Comment by snap608** [comment]
Thanx! You rock! :)
