### ISSUE TITLE
YouTube broken

### ISSUE THREAD

**Issue by 89z** [dotnettools/SharpGrabber#38]
~~~
curl -v 'https://www.youtube.com/get_video_info?video_id=m_Lr5hhlICA&eurl=https://youtube.googleapis.com/v/m_Lr5hhlICA&html5=1&c=TVHTML5&cver=6.20180913'
HTTP/2 404
~~~

**Comment by JavidShoaei** [comment]
Have you updated to 1.5.3?

**Comment by 89z** [comment]
Ah, I didnt see it mark obsolete:

https://github.com/dotnettools/SharpGrabber/blob/3d39c2dab7fefdbe11e0a406c9ccf87676461356/src/SharpGrabber/Internal/Grabbers/YouTube/YouTubeGrabberBase.cs#L87-L95
