### ISSUE TITLE
How I can make a C# console project with your repo?

### ISSUE THREAD

**Issue by zydjohnHotmail** [dotnettools/SharpGrabber#39]
Hello:
I want to use your repo to download some live streaming data with u3m8 URL.
But I want to do some testing to see if I can use your repo in C# console project or not.
I have done this:
I downloaded your repo, and change target platform to x64, and rebuilt solution with 4 projects, and it works.
Then I created one C# console project targetting .NET 5.0, and add project reference for 3 DLLs, which were built by repo target x64 platform.
The 3 DLLs are:
SharpGrabber.Converter.dll
SharpGrabber.Desktop.dll
SharpGrabber.dll
I also install xunit nuget package:
PM> Install-Package xunit -Version 2.4.1
The following is my code:
using DotNetTools.SharpGrabber.Internal.Grabbers;
using System;
using System.Diagnostics;
using Xunit;

namespace SharpGrabberDownload1
{
    class Program
    {
        public static async void Test_YouTube_Normal()
        {
            try
            {
                var grabber = new YouTubeGrabber();
                var result = await grabber.GrabAsync(new Uri("https://www.youtube.com/watch?v=ThUS9fj-mCA"));
                Assert.False(result.IsSecure);
                Assert.Equal(23, result.Resources.Count);
            }
            catch (Exception ex)
            {
                Debug.Print(ex.Message);
            }
        }

        static void Main()
        {
            Test_YouTube_Normal();
        }
    }
}
It is simply one of your file (only one test):
public class GrabTests
in DotNetTools.SharpGrabber.Tests NameSpace.
I can get my program compiled, but when I run it or debug it, nothing happens.  I can’t stop at var result = await grabber.GrabAsync(new Uri("https://www.youtube.com/watch?v=ThUS9fj-mCA"));
The program simply ends without any error message.
Please let me know if it is a correct way to use your repo in a C# console project or in a C# WinForm project. 
If not, then which way is correct?
I want to use your repo in either C# console project or WinForm project, not others.
I am using Windows 10 Version 21H1, and Visual Studio 2019 Version 16.10.4
Thanks,

**Comment by JavidShoaei** [comment]
Write it like this:

	namespace SharpGrabberDownload1
	{
		class Program
		{
			public static async Task Test_YouTube_Normal()
			{
				try
				{
					var grabber = new YouTubeGrabber();
					var result = await grabber.GrabAsync(new Uri("https://www.youtube.com/watch?v=ThUS9fj-mCA"));
					Assert.False(result.IsSecure);
					Assert.Equal(23, result.Resources.Count);
				}
				catch (Exception ex)
				{
					Debug.Print(ex.Message);
				}
			}

			public static Task Main()
			{
				return Test_YouTube_Normal();
			}
		}
	}

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply, I found the issue: I have to install NewtonSoft.Json, then it works.
However, as Microsoft has its own JSON package: system.text.json, I would like to see if could use system.text.json in your library to replace Newtonsoft.json.
Thanks,

**Comment by JavidShoaei** [comment]
Hello there,
Why would you want to do that? The library works independently from your program, and uses `Newtonsoft.Json` due to compatibility. You should keep using `System.Text.Json` in your code, and the library should keep using `Newtonsoft.Json`. What's the problem?

**Comment by zydjohnHotmail** [comment]
Hi,
If it is for compatibility, then it is OK to use Newtonsoft.Json.
Thanks for explanation!
