### ISSUE TITLE
Youtube The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by crippledfaith** [dotnettools/SharpGrabber#42]
https://www.youtube.com/watch?v=4mECX60FVJQ
GrabbedMedia.ResourceUri=
https://r1---sn-h51xq5-q5jl.googlevideo.com/videoplayback?expire=1631161132&ei=zDY5Yej6Iear3LUPs9Ka0Ao&ip=203.95.221.49&id=o-ABO__WkAtQ021lkpUUBN4Q-l21x9nJPZRqZ6fWVyYWFt&itag=137&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278&source=youtube&requiressl=yes&mh=B9&mm=31%2C29&mn=sn-h51xq5-q5jl%2Csn-h5576n7k&ms=au%2Crdu&mv=m&mvi=1&pl=25&gcr=bd&initcwndbps=1133750&vprv=1&mime=video%2Fmp4&ns=SCA4q_Twbe1wjU3a5jP9yzgG&gir=yes&clen=114691908&dur=344.969&lmt=1631121474701980&mt=1631139166&fvip=3&keepalive=yes&fexp=24001373%2C24007246&beids=23886212&c=WEB&txp=5311224&n=XHDKcdJmGD-lvWA&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cgcr%2Cvprv%2Cmime%2Cns%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRgIhAL1ME-AV9Y5eKslMSJKV-yeqqDLQiJqFJ5FE-pnO_2TFAiEA3jMi_dEADFqivW_MV--LadrdIljcjFTQrkHnZ31CxIQ%3D&sig=0QJ8wRAIgUDEKqmHmySZJBwn3Dix4f9BYyLUAsYKtwAVM5Lb6Ld8CIHPzLYegkAbIbPkV9DJyR0mj1GLfhu3B9qtMT7e5_D6o

Most videos in this link are not working https://www.youtube.com/hashtag/vevo

**Comment by JavidShoaei** [comment]
It seems the URL template is correct, but there's a problem with deciphering even though the deciphering function is also working fine! I haven't been able to diagnose the source of the problem, but I'm working on it.

**Comment by JavidShoaei** [comment]
Problem is solved now. Update the `SharpGrabber.YouTube` package.
