### ISSUE TITLE
How to add Grabber with usercredentials?

### ISSUE THREAD

**Issue by michasch64** [dotnettools/SharpGrabber#43]
Hello, is there an example to send a login and receive cookies before grabbing from a site (eg. Instagram, fb etc.)? 
BTW, perfect job!!

**Comment by JavidShoaei** [comment]
Hey there,
Thanks! Unfortunately, that's not possible as of yet. However, I'm occasionally working to add support for services that require login. It shouldn't be much difficult.

**Comment by michasch64** [comment]
Ty for the quick response, looking forward to the solution. Meanwhile I try
myself with a "DefaultCookieHttpClient" but I'm just a hobby C# developer
and might fail on that. If I succeed I will send my solution.

Javid Sh ***@***.***> schrieb am Sa., 18. Sept. 2021, 11:52:

**Comment by JavidShoaei** [comment]
No problem. Make sure to watch the project to be delivered the good news 😃
