### ISSUE TITLE
How to convert m3u8 ts segments to playable file?

### ISSUE THREAD

**Issue by duci95** [dotnettools/SharpGrabber#44]
I have m3u8 playlist and when I choose desired video quality (eg. full HD) how to extract ts files so I can make playable file?

**Comment by JavidShoaei** [comment]
The extraction is rather easy. Just grab the m3u7 file with the grabber. It'd provide you with URLs of ts files.
After you've downloaded all ts files, you can either use the `SharpGrabber.Converter` package to concatenate the ts files together and build the final file, or use ffmpeg executable file to do so.
For a code sample, you can take a look at `SharpGrabber.Desktop` which puts the package mentioned above to use.

**Comment by duci95** [comment]
Thanks mate, but now I am getting this error System.DllNotFoundException: Unable to load DLL  avformat.58 and I have even downloaded this dll

**Comment by JavidShoaei** [comment]
I think you should try downloading the `ffmpeg` build from another source. I personally use the following website:

https://github.com/BtbN/FFmpeg-Builds/releases

Try downloading all shared win64 builds and test which one works for you.

**Comment by duci95** [comment]
Still getting the same error.

**Comment by JavidShoaei** [comment]
Does ffmpeg.exe even run?

**Comment by duci95** [comment]
No, I just get error that no dll is found and I have downloaded it inside the folder that I need.

**Comment by JavidShoaei** [comment]
There's nothing I can do about this. Google it and make sure `ffmpeg.exe` runs flawlessly first.
From what I understand you've downloaded that particular DLL independently. You shouldn't do that. You should download the release as a whole because all DLL files don't necessary match with each other.

**Comment by duci95** [comment]
Ok, thanks mate for help.
