### ISSUE TITLE
Compressed (zipped) Folders Error

### ISSUE THREAD

**Issue by 89z** [dotnettools/SharpGrabber#45]
If I download this:

https://github.com/dotnettools/SharpGrabber/releases/download/desktop3.1/SharpGrabber.Desktop-v3.1.zip

and try to open, I get this:

~~~
Compressed (zipped) Folders Error
Windows cannot open the folder.
The Compressed (zipped) Folder 'D:\Desktop\SharpGrabber.Desktop-v3.1.zip' is
invalid.
~~~

**Comment by JavidShoaei** [comment]
The zip file has the maximum compression and apparently, explorer doesn't support it out of the box.

I compressed this with WinRAR. I'm sure you can use the following free software to open it up as well:

https://www.7-zip.org/download.html

**Comment by 89z** [comment]
Nope:

~~~
Can not open the file as [zip] archive
The file is open as [tar] archive

Open WARNING: Can not open the file as [zip] archive
~~~

**Comment by JavidShoaei** [comment]
OK then, I'm going to re-upload it.

**Comment by JavidShoaei** [comment]
Re-uploaded as an LZMA zip file.

**Comment by JavidShoaei** [comment]
I'm uploading another file that includes `ffmpeg` binaries as well, only for win64.

**Comment by JavidShoaei** [comment]
Done. Check it out [here](https://github.com/dotnettools/SharpGrabber/releases/tag/desktop3.1).
