### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by hey-red** [dotnettools/SharpGrabber#46]
Lastest version of SharpGrabber.Desktop(v3.2)

```
Error:
  An assembly specified in the application dependencies manifest (SharpGrabber.Desktop.deps.json) was not found:
    package: 'Microsoft.Win32.SystemEvents', version: '4.5.0'
    path: 'runtimes/win/lib/netcoreapp2.0/Microsoft.Win32.SystemEvents.dll'
```

Also, maybe best way for GUI app is that have self-contained version. It's can have large size, but works out of box and do not requires installed runtime.

**Comment by JavidShoaei** [comment]
Sorry about that. I'll re-upload the release. And you're right it's a bit large.
