### ISSUE TITLE
Quality Extension Methods

### ISSUE THREAD

**Issue by javidsho** [dotnettools/SharpGrabber#49]
Add a few extension methods to conveniently get highest quality.

**Comment by JavidShoaei** [comment]
> 
> 
> Something like this?
> 
> ```
>     //Highest Bitrate
>     private static GrabbedMedia ChooseHighestBitrateMedia(GrabResult result, MediaChannels channel)
>     {
>         var resources = result.Resources<GrabbedMedia>()
>             .Where(m => m.Channels == channel)
>             .ToList();
> 
>         if (resources.Count == 0)
>             return null;
> 
>         double Highest = 0;
>         int Picked = 0;
> 
>         for (var i = 0; i < resources.Count; i++)
>         {
>             var resource = resources[i];
>             string value = Regex.Replace(resource.BitRateString, "[A-Za-z ]", "");
>             double parsedValue = double.Parse(value);
>             if (parsedValue > Highest)
>             {
>                 Picked = i;
>                 Highest = parsedValue;
>             }
>             //Console.WriteLine($"{i}. {resource.Title ?? resource.FormatTitle ?? resource.Resolution}");
>         }
>         return resources[Picked];
>        
>     }
> ```

Hey there,
Thanks for the code. Did you test it on multiple sources or just YouTube?
