### ISSUE TITLE
How to download m3u8 files and convert to mp3?

### ISSUE THREAD

**Issue by DukeNuken** [dotnettools/SharpGrabber#58]
Hello. 

I am using this code 
```
var grabber = GrabberBuilder.New()
                .UseDefaultServices()
                .AddHls()
                .Build();

 var grabResult = await grabber.GrabAsync(new Uri("https://cs4-9v4.vkuseraudio.net/s/v1/ac/pYZ1qXNzF1JtetJ5187d-Ur6TUGJsFrBugQJeHTMCCL9Lx8LSZUi0DlPe_4JmRDD50P6fOWvDlmld_XCxXxAwyZ5SaU2B1NN9NSyY3UIsagcJdLTVrT7qhcHxg_mS6rrfbrQAQRMn0ZHXEMaJgN3NI4VC3GY_VUIsil_1G7w0DOA5oo/index.m3u8"));
```

and it returns some information, but I do not understand how to download all parts of that m3u8 file to one ts file and then convert it to mp3. Do we have some code example of how to do it?

Duke

**Comment by JavidShoaei** [comment]
Hello there,

Take a look at this example:
https://github.com/dotnettools/SharpGrabber/wiki/03-Examples#grabbing-video-from-an-m3u8-playlist

Don't forget to install the latest NuGet package for `SharpGrabber.Hls`.

**Comment by DukeNuken** [comment]
@JavidShoaei 
Thank you. Thank code works but when I try use the concatenator for build output file I am getting an error 
`Unable to load DLL 'avformat.58 under d:\devel\ffmpeg\': The specified module could not be found.`
Looks like that code is out of date because of official page https://github.com/BtbN/FFmpeg-Builds/releases use "avformat-59.dll" inside the shared folder. How to fix that?

**Comment by JavidShoaei** [comment]
> @JavidShoaei Thank you. Thank code works but when I try use the concatenator for build output file I am getting an error `Unable to load DLL 'avformat.58 under d:\devel\ffmpeg\': The specified module could not be found.` Looks like that code is out of date because of official page https://github.com/BtbN/FFmpeg-Builds/releases use "avformat-59.dll" inside the shared folder. How to fix that?

You're welcome. Try installing the latest version of this NuGet package: `FFMpeg.AutoGen` (Latest one is v4.4.1.1).
See if this fixes the problem.

**Comment by DukeNuken** [comment]
@JavidShoaei  
I am using that FFMpeg.AutoGen (Latest one is v4.4.1.1) and see that error. Looks like a better case just use https://streamlink.github.io/ tool which can download all parts of ts file and then I convert it with ffmpeg to mp3.

**Comment by JavidShoaei** [comment]
Oh in that case, you don't have to use FFMpeg shared libraries at all!
Just use `ffmpeg.exe` command line and it does anything you want.

For example, take a look at the following link:
https://superuser.com/questions/692990/use-ffmpeg-copy-codec-to-combine-ts-files-into-a-single-mp4
