### ISSUE TITLE
Getting exception while grabbing YouTube videos

### ISSUE THREAD

**Issue by Deep-Winter** [dotnettools/SharpGrabber#62]
```
---> System.MissingMethodException: Method not found: 'System.String Jint.Native.JsValue.AsString()'.
2022-01-10T10:37:56+01:00    at DotNetTools.SharpGrabber.MultiGrabber.InternalGrabAsync(IEnumerable`1 candidateGrabbers, Uri uri, CancellationToken cancellationToken, GrabOptions options, IProgress`1 progress)
```

**Comment by javidsho** [comment]
I tried grabbing from YouTube and it showed me no errors.
Please give more details.
The "Method Not Found" error is usually caused by dependency issues. What's the maximum version of Jint used in your project (if you've installed it in your project)?

**Comment by Deep-Winter** [comment]
This is a Video to reproduce the error https://youtu.be/gr8uF04CFWo Not every Video causes the exception. I didn't install Hint in my projects, the implicit used package version is 3.0.0-beta-2036. This is installed with the latest Sharpgrabber version 2.1.0.

**Comment by javidsho** [comment]
Oh now I see the problem. Working on it.

**Comment by javidsho** [comment]
Fixed. Get the package YouTube v1.3.

**Comment by Deep-Winter** [comment]
Thank you for the fast solution!

**Comment by javidsho** [comment]
You're welcome 👍
