### ISSUE TITLE
How Can I Find Mp3 Format?

### ISSUE THREAD

**Issue by honeyhead** [dotnettools/SharpGrabber#64]
If I searched YouTube videos, I could only find mp4 and webm. The audio format does not support mp3, so how can I get it without conversion?

Other websites provide mp3, so it seems to be something that needs to be implemented on the code.

I want to make this into xamarin. so I just want to provide download feature

**Comment by javidsho** [comment]
Well, I don't think you can get it without conversion. Those websites are using the executable version of `ffmpeg` for this purpose. It's extremely easy to convert between all formats with it.
