### ISSUE TITLE
Delete please.

### ISSUE THREAD

**Issue by barissaritas** [dotnettools/SharpGrabber#65]
Do you have a solution for the below part?

// TODO: Instagram is changed and needs user to be authorized before accessing the content

            var match = _graphqlScriptRegex.Match(content);
            if (!match.Success)
                throw new GrabParseException("Failed to obtain metadata from the Instagram page.");

**Comment by javidsho** [comment]
This requires the implementation of an authentication system for the library. It's in my TODO list, I haven't found the time to get it done.

**Comment by javidsho** [comment]
I've started working on this issue.
I'm going to have to include 2FA in the desktop app as well.

**Comment by javidsho** [comment]
Thanks for the info! I'll add this to the library alongside 2FA. I've been a bit busy, I'm so close to implementing the authentication for Instagram.

**Comment by javidsho** [comment]
@89z I tried the workaround with browser and it's not working.
https://www.instagram.com/p/***/?utm_source=ig_web_copy_link&__a=1

**Comment by 89z** [comment]
@javidsho the link you put works for me, it returns a JSON response. However again the site has very strict limits, I think 5 per day or something.

**Comment by javidsho** [comment]
I tried to use InstagramApiSharp's public version, but its API client is apparently obsolete, The authentication doesn't work even though it seems it does! Do you happen to know of a working library for Instagram?

**Comment by barissaritas** [comment]
> InstagramApiSharp'ın herkese açık sürümünü kullanmaya çalıştım, ancak API istemcisi görünüşe göre eski, Kimlik doğrulama çalışıyor gibi görünse de çalışmıyor! Instagram için çalışan bir kütüphane biliyor musunuz?

I do not know.
