### ISSUE TITLE
Very slow download speeds

### ISSUE THREAD

**Issue by bottleblue** [dotnettools/SharpGrabber#72]
Using SharpGrabber Desktop, I tried grabbing multiple youtube vids and they all download super slow. It took almost 10 min. to download an 11MB audio file. Vimeo files also don't work - it gives me a "Grab Error - the URL is not supported" message. I tried https://vimeo.com/692425535. 

Am I supposed to configure something first?

**Comment by javidsho** [comment]
The reason for slow YouTube downloads is that YouTube CDN slows the downloads down significantly when serving as if the user is watching.

As for Vimeo, its URL template has recently changed, I'm trying to fix it right now.

**Comment by bottleblue** [comment]
I was using a tampermonkey youtube script before and it downloads at decent speeds using my browser. Faster if I paste the link into a download manager. This app isn't going to be very useful if it takes hours to download something I can  download in minutes. I would only use this if I had no other option.

**Comment by javidsho** [comment]
The only thing that can work this limitation around is using multiple connections, just like download managers. I had mentioned it over a year ago here: https://github.com/dotnettools/SharpGrabber#contribution

But I've never found the time to do this task.

**Comment by bottleblue** [comment]
Well I hope it'll be improved eventually. Also the gui could use some more options. You can't change the location of temp files and it doesn't look like you can cancel a download in progress without quitting the program. 

Thx for the help
