### ISSUE TITLE
Exception: "Failed to locate source code of container object for helper functions"

### ISSUE THREAD

**Issue by Dav2070** [dotnettools/SharpGrabber#78]
Hey, thanks for creating SharpGrabber. I'm using it in one of my apps and it is very useful for downloading audio tracks from YouTube!

Today, I encountered the following exception when grabbing a YouTube video:
`Failed to locate source code of container object for helper functions.`

It seems you already fixed this issue in the following commit: [869ba54](https://github.com/dotnettools/SharpGrabber/commit/869ba54d8916ace2d1b7f6c208eb2715b6a1ce26)
But the fix is not included in the latest release of SharpGrabber.YouTube on nuget. Could you create a new release with the fix included?

**Comment by javidsho** [comment]
Hey there!
Glad you like it! BTW I live in Germany too :)
Sure the new version is released now

**Comment by Dav2070** [comment]
Perfekt, danke! :)
