### ISSUE TITLE
Use configurable params instead of hardcoding

### ISSUE THREAD

**Issue by JafarAkhondali** [dotnettools/SharpGrabber#8]
https://github.com/dotnettools/SharpGrabber/blob/48146b1f2c2bc90658180305133fafda1012a24f/src/SharpGrabber.Desktop/Downloader.cs#L60

I think it would be cleaner to have a config file that uses this threshold, it would be more readable too.
By the way is `Math.Abs` necessary?

**Comment by JavidShoaei** [comment]
I guess you're right, even if it usually doesn't matter for users to change progress reporting frequency.
