### ISSUE TITLE
Download sooo slow

### ISSUE THREAD

**Issue by Meisterzunge** [dotnettools/SharpGrabber#80]
Downloading a 1MB video takes ca. 2 minutes..

```
var grabber = GrabberBuilder.New()
  .UseDefaultServices()
  .AddYouTube()
  .AddVimeo()
  .Build();

var grabResult = await grabber.GrabAsync(new Uri("someYtVideoUrl"));
var mediaFiles = grabResult.Resources<GrabbedMedia>().ToArray();

using (var client = new HttpClient())
using (var response = await client.GetAsync(mediaFiles[5].ResourceUri))
{
	response.EnsureSuccessStatusCode();
	using (var downloadStream = await response.Content.ReadAsStreamAsync())
	{
		// ...
	}
}
```

Maybe this is a `HttpClient` issue..?

**Comment by javidsho** [comment]
Not at all, it's YouTube that throttles the connection down to a speed sufficient for watching only.
There's only one way to fix that. You'd need to use a download manager, such as [this one](https://github.com/gregyjames/OctaneDownloader) or [this one](https://github.com/bezzad/Downloader).

**Comment by Meisterzunge** [comment]
Nice! Thanks a lot.
