### ISSUE TITLE
Implement odysee grabber

### ISSUE THREAD

**Issue by Meisterzunge** [dotnettools/SharpGrabber#83]
### Discussed in https://github.com/dotnettools/SharpGrabber/discussions/82

<div type='discussions-op-text'>

<sup>Originally posted by **Meisterzunge** February 14, 2023</sup>
Are there plans to implement other straming providers like odysee.com?</div>

**Comment by javidsho** [comment]
It's now available as a separate package.

**Comment by Meisterzunge** [comment]
@javidsho:
Nice! And works quite well!

BTW: I recognized that u use the `DotNetTools.SharpGrabber.Odysee` namespace for the odysee plugin. Why did you differ here compared to similar plugins (like youtube, wich uses `DotNetTools.SharpGrabber`)?

**Comment by javidsho** [comment]
Honestly I did it in a hurry. It should be like Vimeo, didn't check YouTube.
