### ISSUE TITLE
Update SharpGrabber.Converter for ffmpeg 6.0

### ISSUE THREAD

**Issue by hswlab** [dotnettools/SharpGrabber#89]
There are some syntax issues if using the current SharpGrabber.Converter version with ffmpeg 6.0
I have fixed the code in my project so that the syntax errors are gone, but I'm not sure if I did it correctly.
Can someone check if my changes are correct, please? 

It would be also great to have an offocial update in the nuget package manager. I think the last working ffmpeg version that you can use with the current SharpGrabber.Converter is v4.0.6  :) 

### MediaConcatenator.cs (186)
```
ffmpeg.avcodec_parameters_from_context(param, decoder.GetStream()->codec).ThrowOnError();
changed to 
ffmpeg.avcodec_parameters_from_context(param, decoder.CodecContext).ThrowOnError();
```

### MediaMerger.cs (198)
```
if (decoder.CodecId == outputStream->codec->codec_id)
changed to
if (decoder.CodecId == outputStream->codecpar->codec_id)
```

### MediaMuxer.cs (36)
```
stream->codec->flags |= ffmpeg.AV_CODEC_FLAG_GLOBAL_HEADER;
changed to 
stream->event_flags |= ffmpeg.AV_CODEC_FLAG_GLOBAL_HEADER;
```

**Comment by javidsho** [comment]
Your last change is not sufficient for it to work. I'm trying to test if it works with the new changes. I'll push to master and release if it works.

**Comment by javidsho** [comment]
Fixed in the new releases.
