### ISSUE TITLE
PFX signing not supported on .NET Core for .Net Core 3.1

### ISSUE THREAD

**Issue by DiegoAndreColli** [dotnettools/SharpGrabber#9]
I'm trying to make it compile in my machine, I have .Net Core 3.1 installed, and I'm receiving the following errors... I tried some workaround but without success, do you know the cause? Thanks for your work.

  Microsoft.Common.CurrentVersion.targets(3222, 5): PFX signing not supported on .NET Core
  NuGet.Build.Tasks.Pack.targets(198, 5): [NU5026] The file 'C:\projects\Grabber\src\SharpGrabber\bin\Debug\netstandard2.0\SharpGrabber.dll' to be packed was not found on disk.

**Comment by JavidShoaei** [comment]
Please clarify whether you are having problems with the SharpGrabber library or the desktop application.

**Comment by DiegoAndreColli** [comment]
It is an application problem, since I can remove the project, delete desktop folder and the error is the same.

**Comment by JavidShoaei** [comment]
I understand. I could not reproduce your problem, but I think you can easily get rid of this error.
In Visual Studio, navigate to project properties for SharpGrabber. Go to Signing section and uncheck "Sign the assembly". You should be good to go.

**Comment by JavidShoaei** [comment]
I guess it was a configuration problem. I have updated the repo. If you pull or check out again, the problem should be solved.

**Comment by DiegoAndreColli** [comment]
Oh, sorry for not mentioning it before, but I'm using rider not visual studio, maybe that is the reason

**Comment by JavidShoaei** [comment]
No problem. It's *exactly* the same for Rider. I just checked out the repo again and I saw no problem at all. You can just make sure that the "sign the assembly" option is not checked.

**Comment by JavidShoaei** [comment]
So, did it work after all?

**Comment by DiegoAndreColli** [comment]
Well I yes I guess, now I have   Microsoft.Common.CurrentVersion.targets(1175, 5): [MSB3644] The reference assemblies for .NETFramework,Version=v4.6.1 ... bla bla bla... Rider does not work well with global.json (In order to use the correct version when compile) so to be honest, I ended using another library, but thank you anyway, sorry if I was not of great help.
