### ISSUE TITLE
Can you use your repo to download only audio part of m3u8 stream?

### ISSUE THREAD

**Issue by zydjohnHotmail** [dotnettools/SharpGrabber#93]
Hi,
For my project, I have to do this: for some specific m3u8 streams, I need to download only the audio part, then merge the downloaded part into smaller WAV files with 16KHz frequency; so I can use other library to convert the speech to text.
Let me know if it is possible.  If yes, can you show some ideas or some code samples?
Thanks,

**Comment by javidsho** [comment]
Hi
Does the m3u8 stream contain video segments that you want to extract audio from? Or does it contain audio-only segments directly?

**Comment by zydjohnHotmail** [comment]
Hi,
The HLS live stream contains both audio and video data.
Can you write some example code for this?
But I want to run the program target .net 8.0 for Windows for my WinForms project.

**Comment by javidsho** [comment]
I believe it's not possible to grab only audio directly from an HLS stream. You'll need to download everything first and then extract the audio.

**Comment by zydjohnHotmail** [comment]
No, I found how to do this, but it is not easy to do.
